### ISSUE TITLE
Installation procedure 

### ISSUE THREAD

**Issue by GayBondageMaster175** [LilSumac/bash-srp-beta#2]
Any specifics for installing/running this Gamemode? Also, will there be any updates in the future?

**Comment by LilSumac** [comment]
Thanks for the interest, GayBondageMaster175.

This repo is pretty much dead, as it was a brief iteration between the initial [Alpha](https://github.com/LilSumac/bash-srp-alpha) experimental release and the [current](https://github.com/LilSumac/bash) engine/schema-based project I'm working on in my spare time. None of these projects really 'work', at least not reliably enough to use on a public server. You can try slapping any of them into your gamemodes/ folder and seeing if it runs, but I doubt it will do anything besides spit out some startup debug logs.

Feel free to poke around the code and see how I implemented stuff, though. The Alpha contains kinda crappy code but has a lot of features and the Beta is nearly empty besides boilerplate stuff, while the current iteration is still in the framework stage but I actually work on it (haven't committed my changes recently) and is better written IMO.

Let me know if you have any further questions!
